config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get "/about" => "home#about"
  resources :users
  resources :posts do
  	resources :comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user, optional: true
	attachment :image
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
		user_path(current_user.id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
    post = Post.find(params[:post_id])
    @comment = post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
      Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
      redirect_to request.referer
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def new
  	@post = Post.new # 入力フォームを作成
  end
  
  def create
  	@post = Post.new(post_params)
  	# 保存が成功した時と失敗した時の条件分岐
  	if @post.save
  		redirect_to posts_path #保存された場合の移動先を指定。
  	else
  		@posts = Post.all
  		render new_post_path # 保存が失敗した時の移動先
  	end
  end

  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = @post.comments.build
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:location_name, :image, :caption, :explanation, :address, :height, :fence, :width )
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to("/")
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<h1>ページの説明書きます</h1>

app/views/home/index.html.erb
<h1>トップページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WallLocation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-image">
    <!-- ヘッダー設定 -->
    <header class="navbar navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-left">
            <% if user_signed_in? %>
              <li><%= link_to 'wall-location', user_path(current_user) %></li>
            <% else %>
              <li><%= link_to 'wall-location' %></li>
            <% end %>
          </ul>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとサインアウト時の表示を変更-->
            <% if user_signed_in? %>
              <li><%= link_to 'home', user_path(current_user) %></li>
              <li><%= link_to 'search' %></li>
              <li><%= link_to 'posts', posts_path %></li>
              <li><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'home', root_path %></li>
              <li><%= link_to 'about', about_path %></li>
              <li><%= link_to 'sign up', new_user_registration_path %></li>
              <li><%= link_to 'login', new_user_session_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<table class="table">
  	<thead>
  		<tr>
  			<th>場所</th>
  			<th>写真</th>
  			<th>題名</th>
  			<th>本文</th>
  			<th>住所</th>
  			<th>高さ</th>
  			<th>幅</th>
  			<th>フェンス</th>
  		</tr>
  	</thead>
  	<tbody>
      <% @posts.each do |post| %>
  		<tr>
  			<td>
  			  <%= link_to post_path(post) do %>
  			    <%= post.location_name %>
  			  <% end %>
  			</td>
  			<td>
  		      <%= link_to post_path(post) do %>
  			    <%= attachment_image_tag post, :image %>
  		      <% end %>
  		    </td>
  			<td><%= post.caption %></td>
  			<td><%= post.explanation %></td>
  			<td><%= post.address %></td>
  			<td><%= post.height %></td>
  			<td><%= post.width %></td>
  			<td><%= post.fence %></td>
  		</tr>
  	  <% end %>
  	</tbody>
</table>

app/views/posts/new.html.erb
<!-- エラーメッセージ表示-->
<% if @post.errors.any? %>
  <h3><%= @post.errors.count %>error occurrence</h3><!--エラーメッセ-->
  <ul>
    <% @post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<!-- エラーメッセージ表示-->

<h1>壁登録ページ</h1>
<%= form_for(@post) do |f| %>
  <div>
  	<%= f.label :名前 %>
	<%= f.text_field :location_name, placeholder:"(例)○○公園" %>
  </div>
  <div>
  	<%= f.label :写真 %>
	<%= f.attachment_field :image, onChange:"imgPreView(event)" %>
	<div id="preview"></div>
  </div>
  <div>
  	<%= f.label :タイトル %>
	<%= f.text_field :caption %>
  </div>
  <div>
  	<%= f.label :オススメポイント %>
	<%= f.text_area :explanation %>
  </div>
  <div>
  	<%= f.label :住所 %>
	<%= f.text_field :address %>
  </div>
  <div>
  	<%= f.label :壁の高さ %>
	<%= f.text_field :height %>
  </div>
  <div>
  	<%= f.label :壁の幅 %>
	<%= f.text_field :width %>
  </div>
  <div>
  	<%= f.label :フェンスの有無 %>
	<%= f.text_field :fence %>
  </div>
    <%= f.submit "壁登録" %>
<% end %>

app/views/posts/show.html.erb
<table class="table">
  	<thead>
  		<tr>
  			<th>場所</th>
  			<th>写真</th>
  			<th>題名</th>
  			<th>本文</th>
  			<th>住所</th>
  			<th>高さ</th>
  			<th>幅</th>
  			<th>フェンス</th>
  		</tr>
  	</thead>
  	<tbody>
  		<tr>
  			<td><%= @post.location_name %></td>
  			<td><%= attachment_image_tag @post, :image %></td>
  			<td><%= @post.caption %></td>
  			<td><%= @post.explanation %></td>
  			<td><%= @post.address %></td>
  			<td><%= @post.height %></td>
  			<td><%= @post.width %></td>
  			<td><%= @post.fence %></td>
        <td><%= link_to "投稿削除", post_path, method: :delete %></td>
  		</tr>
  	</tbody>
</table>
<div>
  <p>コメント一覧</p>
  <% @comments.each do |comment| %>
    <div>
      <%= comment.user.name unless comment.user.blank? %>
        <%= comment.content %>
        <% if comment.user == current_user%>
          <%= link_to "削除", post_comment_path(comment.post, comment), method: :delete, remote: true %>
        <% end %>
      <% end %>
  <% if user_signed_in? %>
    <%= form_with(model: [@post, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h4>ユーザー詳細</h4>

<%= form_for(@user) do |f| %>
  <div>
  	<%= f.label :名前 %>
	  <%= f.text_field :name %>
  </div>
  <div>
  	<%= f.label :プロフィール画像 %>
	  <p><%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "100x100" %></p>
  </div>
  <div>
  	<%= f.label :登録画像 %>
	  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", onChange:"imgPreView(event)" %>
	  <div id="preview"></div>
  </div>
  <div>
  	<%= f.label :自己紹介 %>
	  <p><%= f.text_area :introduction %><p>
  </div>
	<%= f.submit "情報を更新" %>
  <%= link_to "退会する", user_path(@user), method: :delete, data: { confirm: 'アカウント情報・投稿が全て削除されます。本当に退会しますか？' } %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<% @users.each do |user| %>
<!-- 写真か名前クリックするとユーザーの詳細ページに移行 -->
<%= link_to user_path(user) do %>
<%= attachment_image_tag user, :profile_image_id, size: "100x100", class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
<%= user.name %>
<% end %>


<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>
<div class="container">
  <div class="row">
    <div class="col-xs-10">
      <table class="table">
        <tbody>
	      <tr>
	　      <td>プロフィール画像</td>
	       <td><%= attachment_image_tag @user, :profile_image, size: "100x100", fallback: "no_image.jpg" %></td>
	      </tr>
	      <tr>
	        <td>名前</td>
	        <td><%= @user.name %></td>
	      </tr>
	      <tr>
	        <td>自己紹介</td>
	        <td><%= @user.introduction %></td>
	      </tr>
        </tbody>
      </table>
      <div><%= link_to "壁を登録", new_post_path %></div>
      <div><%= link_to "情報を編集する", edit_user_path(@user) %></div>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>